export const CONDO_PROPERTY_DATA = [
    {label: "Address", key: "propertyAddress"},
    {label: "Price", key: "purchasePrice", displayType: "currency"},
    {label: "Down payment", key: "downPaymentAmount", displayType: "currency"},
    {label: "Mortgage (monthly)", key: "monthlyPayment", displayType: "currency"},
    {label: "Property Taxes", key: "monthlyTaxesTotal", displayType: "currency"},
    {label: "PMI", key: "pMIAmount", displayType: "currency"},
    {label: "HOA fees / assessment", key: "assessmentMonthlyTotal", displayType: "currency"},
    {label: "Insurance", key: "insuranceMonthlyTotal", displayType: "currency"},
    {label: "Others", key: "otherMonthlyTotal", displayType: "currency"},
    {label: "Total Monthly payment", key: "estimatedPayment", displayType: "currency", cellClass: 'bold'},
];

export const CONDO_LOCALSTORAGE_KEYS = [
    "propertyAddress",
    "purchasePrice",
    "downPaymentPercent",
    "interestRate",
    "numberOfYears",
    "taxes",
    "taxes1Frequency",
    "taxes2",
    "taxes2Frequency",
    "insurance",
    "insuranceFrequency",
    "associationFees1",
    "associationFee1Frequency",
    "associationFees2",
    "associationFee2Frequency",
    "otherFees",
    "otherFeesFrequency"
];

export const MULTIFAMILY_PROPERTY_DATA = [
    {label: "MLS ID Number", key: "mLSIDNumber"},
    {label: "Address", key: "addressOfProperty"},
    {label: "Cap Rate", key: "capRate", displayType: "percent"},
    {label: "Net Operating Income", key: "netOperatingIncome", displayType: "currency"},
    {label: "Purchase Price", key: "purchasePrice", displayType: "currency"},
    {label: "Annual Debt Service", key: "annualDebtService", displayType: "currency"},
    {label: "Real Estate Taxes (Yearly)", key: "realEstateTaxesYearly", displayType: "currency"},
    {label: "Annual Gross Income", key: "annualGrossIncome", displayType: "currency"},
    {label: "Annual Fixed Expenses", key: "annualFixedExpenses", displayType: "currency"},
    {label: "Desired Cap Rate", key: "desiredCapRate", displayType: "percent"}
];

export const MULTIFAMILY_LOCALSTORAGE_KEYS = [
    "mLSIDNumber",
    "addressOfProperty",
    "capRate",
    "downPayment",
    "electric",
    "intervalElectric",
    "gas",
    "intervalGas",
    "water",
    "intervalWater",
    "maintenancePaymentAmount",
    "intervalMaintenance",
    "insurancePaymentAmount",
    "intervalInsurance",
    "scavengerPaymentAmount",
    "intervalScavenger",
    "otherMiscPaymentAmount1",
    "intervalOtherMisc1",
    "otherMiscExpense2",
    "otherMiscExpense3",
    "otherMiscExpense4",
    "otherMiscExpense5",
    "rentUnit1",
    "rentUnit2",
    "rentUnit3",
    "rentUnit4",
    "rentUnit5",
    "rentUnit6",
    "rentUnit7",
    "rentUnit8",
    "rentUnit9",
    "rentUnit10",
    "rentUnit11",
    "rentUnit12",
    "showMoreRentInputs",
    "rentParking",
    "otherMiscellaneous1",
    "interestRate",
    "loanTermInYears",
    "netOperatingIncome",
    "purchasePrice",
    "annualDebtService",
    "realEstateTaxesYearly",
    "annualGrossIncome",
    "annualFixedExpenses",
    "desiredCapRate"
];
