export const CONDO_PROPERTY_DATA = [
    {label: "Property Data", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Address", key: "propertyAddress"},
    {label: "Price", key: "purchasePrice", displayType: "currency"},
    {label: "Down payment", key: "downPaymentAmount", displayType: "currency"},
    {label: "Mortgage (monthly)", key: "monthlyPayment", displayType: "currency"},
    {label: "Property Taxes", key: "monthlyTaxesTotal", displayType: "currency"},
    {label: "PMI", key: "pMIAmount", displayType: "currency"},
    {label: "HOA fees / assessment", key: "assessmentMonthlyTotal", displayType: "currency"},
    {label: "Insurance", key: "insuranceMonthlyTotal", displayType: "currency"},
    {label: "Others", key: "otherMonthlyTotal", displayType: "currency"},
    {label: "Total Monthly payment", key: "estimatedPayment", displayType: "currency", cellClass: 'bold'},
];

export const CONDO_LOCALSTORAGE_KEYS = [
    "propertyAddress",
    "purchasePrice",
    "downPaymentPercent",
    "interestRate",
    "numberOfYears",
    "taxes",
    "taxes1Frequency",
    "taxes2",
    "taxes2Frequency",
    "insurance",
    "insuranceFrequency",
    "associationFees1",
    "associationFee1Frequency",
    "associationFees2",
    "associationFee2Frequency",
    "otherFees",
    "otherFeesFrequency"
];

export const MULTIFAMILY_PROPERTY_DATA = [
    {label: "MLS ID Number", key: "mLSIDNumber"},
    {label: "Address", key: "addressOfProperty"},
    // {label: "Mortgage Info", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Net Operating Income", key: "netOperatingIncome", displayType: "currency", cellType: "th"},
    {label: "Cap Rate", key: "capRate", displayType: "percent"},
    {label: "Gross Rent Multiplier", key: "grossRentMultiplier", displayType: "percent"},
    {label: "Cash on Cash Return", key: "cashOnCashReturn", displayType: "percent"},
    {label: "Total Cash Invested", key: "totalCashInvested", displayType: "currency"},
    {label: "Desired Cap Rate purchase price", key: "desiredCapRatePurchasePrice", displayType: "currency"},
    {label: "Purchase Price", key: "purchasePrice", displayType: "currency"},
    // ADD DIVIDER
    {label: "Debt Service and RE Taxes", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Annual Real Estate Taxes", key: "realEstateTaxesYearly", displayType: "currency"},
    {label: "Monthly Debt Service + RE Taxes", key: "monthlyDebtServicePlusRETaxes", displayType: "currency"},
    {label: "Annual Debt Service + RE Taxes", key: "annualDebtServicePlusRETaxes", displayType: "currency"},
    // ADD DIVIDER
    {label: "Income", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Monthly Gross Income", key: "monthlyGrossIncome", displayType: "currency"},
    {label: "Annual Gross Income", key: "annualGrossIncome", displayType: "currency"},
    // ADD DIVIDER
    {label: "Expenses", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Monthly Property Expenses", key: "monthlyExpensesTotal", displayType: "currency", cellType: "td"},
    {label: "Annual Property Expenses", key: "annualExpensesTotal", displayType: "currency", cellType: "td"},
    // ADD DIVIDER
    {label: "Summary", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Monthly Cash Flow", key: "monthlyCashFlow", displayType: "currency", cellType: "td"},
    {label: "Annual Cash Flow", key: "yearlyCashFlow", displayType: "currency", cellType: "td"},
    // Monthly Gross Income
    {rowType:"pagebreak"},
    {label: "Monthly Gross Income", key: "tbd", displayType: "divider", rowType: "divider"},
    {label: "Rent Unit 1", key: "rentUnit1", displayType: "currency"},
    {label: "Rent Unit 2", key: "rentUnit2", displayType: "currency"},
    {label: "Rent Unit 3", key: "rentUnit3", displayType: "currency"},
    {label: "Rent Unit 4", key: "rentUnit4", displayType: "currency"},
    {label: "Rent Unit 5", key: "rentUnit5", displayType: "currency"},
    {label: "Rent Unit 6", key: "rentUnit6", displayType: "currency"},
    {label: "Rent Unit 7", key: "rentUnit7", displayType: "currency"},
    {label: "Rent Unit 8", key: "rentUnit8", displayType: "currency"},
    {label: "Rent Unit 9", key: "rentUnit9", displayType: "currency"},
    {label: "Rent Unit 10", key: "rentUnit10", displayType: "currency"},
    {label: "Rent Unit 11", key: "rentUnit11", displayType: "currency"},
    {label: "Rent Unit 12", key: "rentUnit12", displayType: "currency"},
    {label: "Rent Parking", key: "rentParking", displayType: "currency"},
    {label: "Other Miscellaneous Income 1", key: "otherMiscellaneous1", displayType: "currency"},
    // Monthly Expenses
    {label: "Monthly Expenses", key: "tbd", displayType: "divider", rowType: "divider", cellType: "td"},
    {label: "Real Estate Taxes (monthly)", key: "realEstateTaxesMonthly", displayType: "currency"},
    {label: "Electric", key: "electricMonthlyExpense", displayType: "currency"},
    {label: "Gas", key: "gasMonthlyExpenses", displayType: "currency"},
    {label: "Water", key: "waterMonthlyExpenses", displayType: "currency"},
    {label: "Scavenger", key: "scavengerMonthlyExpense", displayType: "currency"},
    {label: "Other/Misc", key: "otherMonthlyExpense", displayType: "currency"},
    {label: "Insurance", key: "insuranceMonthlyExpense", displayType: "currency"},
    {label: "Maintenance", key: "maintenanceMonthlyExpense", displayType: "currency"},
];

export const MULTIFAMILY_LOCALSTORAGE_KEYS = [
    "mLSIDNumber",
    "addressOfProperty",
    "capRate",
    "downPayment",
    "electric",
    "intervalElectric",
    "gas",
    "intervalGas",
    "water",
    "intervalWater",
    "maintenancePaymentAmount",
    "intervalMaintenance",
    "insurancePaymentAmount",
    "intervalInsurance",
    "scavengerPaymentAmount",
    "intervalScavenger",
    "otherMiscPaymentAmount1",
    "intervalOtherMisc1",
    "otherMiscExpense2",
    "otherMiscExpense3",
    "otherMiscExpense4",
    "otherMiscExpense5",
    "rentUnit1",
    "rentUnit2",
    "rentUnit3",
    "rentUnit4",
    "rentUnit5",
    "rentUnit6",
    "rentUnit7",
    "rentUnit8",
    "rentUnit9",
    "rentUnit10",
    "rentUnit11",
    "rentUnit12",
    "showMoreRentInputs",
    "rentParking",
    "otherMiscellaneous1",
    "interestRate",
    "loanTermInYears",
    "netOperatingIncome",
    "purchasePrice",
    "annualDebtService",
    "realEstateTaxesYearly",
    "annualGrossIncome",
    "annualFixedExpenses",
    "desiredCapRate"
];
